[yarn]
registry = "https://registry.yarnpkg.com/"
home = "https://yarnpkg.com"

[npm]
registry = "https://registry.npmjs.org/"
home = "https://www.npmjs.org"

[tencent]
registry = "https://mirrors.cloud.tencent.com/npm/"
home = "https://mirrors.cloud.tencent.com/npm/"

[taobao]
registry = "https://registry.npmmirror.com/"
home = "https://npmmirror.com/"

[github]
registry = "https://npm.pkg.github.com/"
home = "https://npm.pkg.github.com/"

[npmMirror]
registry = "https://skimdb.npmjs.com/registry/"
home = "https://skimdb.npmjs.com/"
